# Generated by Django 5.1.3 on 2025-06-23 17:13

import django.db.models.deletion
import multiselectfield.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(blank=True, decimal_places=10, default=0.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=10, default=0.0, max_digits=10)),
                ('isFavorite', models.BooleanField(default=False)),
                ('yearsExperience', models.IntegerField(default=0)),
                ('patientsNumber', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, upload_to='photos')),
                ('consultation', models.IntegerField(default=0)),
                ('phoneNuber', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=100)),
                ('sepciality', models.CharField(choices=[('cardiology', 'cardiology'), ('vascular', 'vascular'), ('pulmonology', 'pulmonology'), ('dermatology', 'dermatology'), ('urology', 'urology'), ('orthopedics', 'orthopedics')], max_length=15)),
                ('services', multiselectfield.db.fields.MultiSelectField(choices=[('test1', 'test1'), ('test2', 'test2'), ('test3', 'test3'), ('test4', 'test4'), ('test5', 'test5')], max_length=29)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
