# Generated by Django 5.1.3 on 2025-06-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='phoneNuber',
            new_name='phoneNumber',
        ),
    ]
