# Generated by Django 5.1.3 on 2025-06-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0002_rename_phonenuber_doctor_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phoneNumber',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
