# Generated by Django 5.1.3 on 2025-06-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_availability_timeslot_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='slot_duration',
            field=models.IntegerField(default=30),
        ),
    ]
