# Generated by Django 5.1.3 on 2025-07-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_availability_slot_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='sepciality',
            field=models.CharField(choices=[('cardiology', 'cardiology'), ('dentist', 'dentist'), ('eye_doctor', 'eye_doctor'), ('dermatology', 'dermatology')], max_length=15),
        ),
    ]
