# Generated by Django 5.1.3 on 2025-07-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_alter_doctor_sepciality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
