# Generated by Django 5.2 on 2025-08-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0008_familymember_medicalreport_labtestimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='slot_duration',
        ),
    ]
