# Generated by Django 5.2 on 2025-08-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0009_remove_availability_slot_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='consultation',
            field=models.IntegerField(default=30),
        ),
    ]
