# Generated by Django 5.2.5 on 2025-08-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0014_alter_availability_week_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='labTestImage',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='reportImage',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
        migrations.DeleteModel(
            name='LabTestImage',
        ),
    ]
