# Generated by Django 5.2 on 2025-08-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0015_medicalreport_labtestimage_medicalreport_reportimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='date',
            field=models.DateField(default='2002-10-10'),
            preserve_default=False,
        ),
    ]
