# Generated by Django 5.2 on 2025-08-25 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0016_availability_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['date']},
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('doctor', 'date')},
        ),
    ]
