# Generated by Django 5.2 on 2025-09-04 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0017_alter_availability_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='sepciality',
            field=models.CharField(choices=[('cardiology', 'cardiology'), ('dentist', 'dentist'), ('ophthalmology', 'eye_doctor'), ('neurology', 'dermatology'), ('pulmonology', 'pulmonology')], max_length=15),
        ),
    ]
