# Generated by Django 5.2 on 2025-09-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0018_alter_doctor_sepciality'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
